[fix] Add -D__STDC_FORMAT_MACROS to FLAGS for C99
Add -D__STDC_FORMAT_MACROS flag to FLAGS in
Makefile. ISO C99 requires this predef for C++
clients before including inttypes.h. To avoid
doing this each time we instead add it to flags.

Fixes issues where compiler complains at vcfReader.cpp
i.e. vcfReader.cpp:307:38: error: expected ')' before 'PRId64'

resolves #397
resolves #524
resolves #535